# NumPy - Constructors

In [41]:
import numpy as np

- Here we are starting with Constructors in NumPY. These are functions that help us define and initialize our data sets.
- To create a new numpy array, use the method "array" and feed it some data.
- Note that normally, we don't type out all the numbers we want to fill our arrays because our arrays are usually very large. Rather we use other functions to fill them.

In [42]:
A = np.array([1, 2, 3])
print(A.shape)
A

(3,)


array([1, 2, 3])

- Below, we see that if we fill with zeros, we indicate the (number of columns, number of rows) inside of () because the method "zeros" takes a tuple.

In [43]:
B = np.zeros((3, 2))
B

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

- The size method allows us to see the total number of elements present in all rows and columns.

In [44]:
C = np.ones((3, 4))
C.size

12

- This is less useful, but you can use the full function and dimentions followed by the value to fill and you can quickly fill an ndim array with these values.

In [45]:
D = np.full((2, 3), 9)
D

array([[9, 9, 9],
       [9, 9, 9]])

- Often in machine learning, we want to initialize with random values. The following are useful in this case.
- Using random.randn will return a random set of numbers for the size of the array you indicate.
- randn will find random numbers with a normal distribution around 0.
- Also available is rand (without n). This will give a random sample between 0 and 1, but normally for statistics, they use a random number on a (n)ormal distribution.

In [46]:
# np.random.seed(0) # You can assign a seed like in C with rand in the stdlib
np.random.randn(3, 4)

array([[ 1.07491832, -0.06113484, -0.37883662,  0.66553464],
       [ 1.72271453, -1.32896095,  0.02997015, -1.30470232],
       [-0.57072048, -0.40788309,  0.69826812,  0.86653835]])

- Linspace will let us determin how many spaces we want to fill in a given range. It will do the math for us to evenly add numbers to the array.

In [47]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

- Slightly different, if we want to make an array and indicate the step size we can use the arange function.

In [48]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

- Most of these constructors have an attribute called dtype that is set to float by default.
- dtype indicates the data type of the value to be entered in our arrays.
- By default these are floats, but can be changed easily.
- The following will generate values with the type float64

In [49]:
np.linspace(0, 10, 20, dtype=np.float64)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

- By contrast, here is the same code but with a float16

In [50]:
np.linspace(0, 10, 20, dtype=np.float16)

array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)

## MANIPULATION

In [51]:
A = np.zeros((3, 2))
B = np.ones((3, 2))

In [52]:
print(A)


[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [53]:
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


- We can use hstack and vstack to glue arrays together.
- Below we use hstack:

In [54]:
C = np.hstack((A, B))
C

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [55]:
D = np.vstack((A, B))
D

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

- You can use the concatinate method to accomplish the same thing.
- Note here, you have to indicate the direction of the axis you are gonig to add to.
    - Axis 0 = vertical axis
    - Axis 1 = horizontal axis

In [56]:
C = np.concatenate((A, B), axis=1)
C

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [57]:
D = np.concatenate((A, B), axis=0)
D

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

- Next we have reshape. This allows us to change the shape of the array by rearanging the cells.
- Notice that we start with the first element, move horizontally and add to the new table element by element.

In [58]:
D.size
D = D.reshape((3, 4))
D

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

- Sometimes if you create a new array, you'll find that your shape does not have a height if it's one dimentional.

In [59]:
A = np.array([1, 2, 3])
A.shape

(3,)

- To add a height dimention to this, you can run a reshape on your array to give it a height.

In [60]:
A = A.reshape((A.shape[0], 1))
A.shape

(3, 1)

- Likewise, if we have a trailing 1 and we don't want it, we can use squeeze.

In [61]:
A = A.squeeze()
A.shape

(3,)

- Finally, we have a method called ravel that allows us to take a multi-dimentional array and make it one dimentional.

In [62]:
print(D.shape)
D

(3, 4)


array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
D = D.ravel()
print(D.shape)
D

(12,)


array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.])