In [1]:
import numpy as np

- Here we are starting with Constructors in NumPY. These are functions that help us define and initialize our data sets.
- To create a new numpy array, use the method "array" and feed it some data.
- Note that normally, we don't type out all the numbers we want to fill our arrays because our arrays are usually very large. Rather we use other functions to fill them.

In [2]:
A = np.array([1, 2, 3])
print(A.shape)
A

(3,)


array([1, 2, 3])

- Below, we see that if we fill with zeros, we indicate the (number of columns, number of rows) inside of () because the method "zeros" takes a tuple.

In [3]:
B = np.zeros((3, 2))
B

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

- The size method allows us to see the total number of elements present in all rows and columns.

In [4]:
C = np.ones((3, 4))
C.size

12

- This is less useful, but you can use the full function and dimentions followed by the value to fill and you can quickly fill an ndim array with these values.

In [5]:
D = np.full((2, 3), 9)
D

array([[9, 9, 9],
       [9, 9, 9]])

- Often in machine learning, we want to initialize with random values. The following are useful in this case.
- Using random.randn will return a random set of numbers for the size of the array you indicate.
- randn will find random numbers with a normal distribution around 0.
- Also available is rand (without n). This will give a random sample between 0 and 1, but normally for statistics, they use a random number on a (n)ormal distribution.

In [6]:
# np.random.seed(0) # You can assign a seed like in C with rand in the stdlib
np.random.randn(3, 4)

array([[ 0.13020176, -0.35205647,  0.02076248,  0.97065849],
       [ 1.22164499, -0.53348349,  1.24676145, -1.8979541 ],
       [-1.19030106, -0.11157463,  0.39042127,  0.9835859 ]])

- Linspace will let us determin how many spaces we want to fill in a given range. It will do the math for us to evenly add numbers to the array.

In [7]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

- Slightly different, if we want to make an array and indicate the step size we can use the arange function.

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

- Most of these constructors have an attribute called dtype that is set to float by default.
- dtype indicates the data type of the value to be entered in our arrays.
- By default these are floats, but can be changed easily.
- The following will generate values with the type float64

In [9]:
np.linspace(0, 10, 20, dtype=np.float64)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

- By contrast, here is the same code but with a float16

In [10]:
np.linspace(0, 10, 20, dtype=np.float16)

array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)