## Indexing Slicing and Masking

- Indexing is accessing values in an array. This array could be of n dimentions.

In [1]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
A[0, 0]

1

- Slicing is when we take we an array like the one above and we take only portions of the code.

In [3]:
A[:, 0]

array([1, 4, 7])

In [5]:
A[0, :]     # Both these are the same. Python defaults to showing a row when a single number is present.
A[0]

array([1, 2, 3])

- If we want a block we use a colon with the start and end of the data we want.
- The end number indicates the index where to stop, but will not include this index' data.

In [6]:
A[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [7]:
A[:, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

- Rather than edit our original data set, we normally do something called "Subsetting".
- This is where we make a new data set out of a subset of the original.

In [8]:
B = A[:, 1:3]
B

array([[2, 3],
       [5, 6],
       [8, 9]])

- We can also edit data with simple expressions.

In [9]:
B[0] = 10
B

array([[10, 10],
       [ 5,  6],
       [ 8,  9]])

## Boolian Indexing

- Below we are going to create a boolian mask of some data.
- We start with a 5 by 5 grid of random integers between 1 and 10.
- We can then make a mask simply by using a boolian operator on the array.

In [17]:
A = np.random.randint(0, 10, [5, 5])
A

array([[6, 8, 6, 1, 6],
       [2, 1, 3, 9, 3],
       [3, 0, 3, 2, 9],
       [9, 6, 4, 3, 9],
       [8, 9, 1, 4, 1]])

In [18]:
A < 5

array([[False, False, False,  True, False],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False],
       [False, False,  True,  True, False],
       [False, False,  True,  True,  True]])

- We can take it a step further and edit the original by using the mask.
- Below we take all the values less than 5 and set them equal to 10.

In [15]:
A[A<5] = 10
A

array([[ 9,  8, 10,  9, 10],
       [ 9, 10,  5,  5, 10],
       [10, 10,  8,  6, 10],
       [10, 10, 10,  9, 10],
       [10,  9,  8,  5, 10]])

- Masking data in this way is very useful for certain applications.
    - For example, images are large arrays of data essentially. We can use these methods to edit certain values in an image if we need to.
- We can also use this technique to find values that are in a range.

In [19]:
A[(A<5) & (A>2)] = 10   # If a number is less than 5 and greater than 2, change it to a 10.
A

array([[ 6,  8,  6,  1,  6],
       [ 2,  1, 10,  9, 10],
       [10,  0, 10,  2,  9],
       [ 9,  6, 10, 10,  9],
       [ 8,  9,  1, 10,  1]])

- We can also create new tables with the data in a certain range, then find it's shape.
- By doing this, we can find how many elements in an array have a value in a certain range.

In [20]:
A[A<5].shape

(7,)