# NumPy Broadcasting

- Broadcasting referes to when we take an array of (n, n) and do some math to it across an entire row or column.
- This method is "dangerous" however becuase there are certain circumstances that lead to it being slower in C than in python.
    - Further reading: {{https://numpy.org/doc/stable/user/basics.broadcasting.html}}
- Matrix arithmetic works well for when the arrays are of the same dimension, however, when we use arrays of different sizes, there can be issues.
- To simplify this, here are some basic rules to use to do matrix arrithmetic. 
- Rules:
    - When we look at an array, we have first the columns then the rows (columns, rows).
    - The rules can be demonstrated here:
        - Given an array A has dimensions of (2, 3), in order to perform math on this array, array B must satisfy one of the following:
            - B has dimensions (2, 3)
                - Both columns and rows are the same.
            - B has dimentions (2, 1)
                - Columns is the same, and rows is 1.
            - B has dimentions (1, 2)
                - Columns is 1, and rows is the same.
            - B has dimention (1, 1)
                - This means B is a number and is considered a scalar.
            - Using an array of dimentions (2, 2) will not work.

In [39]:
import numpy as np
import time
np.random.seed(seed=int(time.time()))
A = np.random.randint(0, 10, [2, 3])

In [40]:
B = np.ones((2, 3))
print(f"A:\n{A}")
print(f"B:\n{B}")
A + B                   # Works with 2, 3

A:
[[6 0 4]
 [6 9 0]]
B:
[[1. 1. 1.]
 [1. 1. 1.]]


array([[ 7.,  1.,  5.],
       [ 7., 10.,  1.]])

In [41]:
B = np.ones((2, 1))     # Change to 2, 1. Works.
print(f"A:\n{A}")
print(f"B:\n{B}")
A + B

A:
[[6 0 4]
 [6 9 0]]
B:
[[1.]
 [1.]]


array([[ 7.,  1.,  5.],
       [ 7., 10.,  1.]])

In [42]:
B = np.ones((1, 3))     # Change to 1, 3. Works.
print(f"A:\n{A}")
print(f"B:\n{B}")
A + B

A:
[[6 0 4]
 [6 9 0]]
B:
[[1. 1. 1.]]


array([[ 7.,  1.,  5.],
       [ 7., 10.,  1.]])

In [43]:
B = 2                   # Works with scalars.
print(f"A:\n{A}")
print(f"B:\n{B}")
A * 2

A:
[[6 0 4]
 [6 9 0]]
B:
2


array([[12,  0,  8],
       [12, 18,  0]])

In [44]:
B = np.ones((2, 2))     # Change to 2, 2. Does not work.
print(f"A:\n{A}")
print(f"B:\n{B}")
A + B

A:
[[6 0 4]
 [6 9 0]]
B:
[[1. 1.]
 [1. 1.]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

- Moving further, it can be a little surprising then, that adding two matrixes with a single row or column causes a resulting array of larger size in both dimensions.
- Example: (4, 1) + (1, 4) = (4, 4)

In [60]:
A = np.ones((4, 1))
B = np.ones((1, 4))
print(f"A:\n{A}")
print(f"B:\n{B}")
A + B

A:
[[1.]
 [1.]
 [1.]
 [1.]]
B:
[[1. 1. 1. 1.]]


array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

- In addition, if we use an incomplete array of 1's we'll get the same result.
- When we use a dimension like (X, ) where there is no last dimension, the X is considered the last dimension in the table.
- WARNING: This is where broadcasting can be dangerous.
    - If you have some arrays that end in ", " you can accidentally broadcast some data with this by accident so you have to be careful with your data.
    - For this reason, you should always verify your dimensions and use reshape() when needed.
    - For example, if you have a data set that is (100, 1) and another that is (100, ) when you try to add these, you'll get a resulting data set that is (100, 100) which would obviously mess things up a little.

In [59]:
A = np.random.randint(0, 10, [4, 1])
B = np.ones((4, ))
print(f"A:\n{A}\n")
print(f"B:\n{B}\n")
print(f"A + B:\n{A + B}\n")

A:
[[3]
 [5]
 [9]
 [7]]

B:
[1. 1. 1. 1.]

A + B:
[[ 4.  4.  4.  4.]
 [ 6.  6.  6.  6.]
 [10. 10. 10. 10.]
 [ 8.  8.  8.  8.]]



- To fix this we can use reshape and our data to give it a new dimension.

In [58]:
A = np.random.randint(0, 10, [4, 1])
B = np.ones((4, ))
B = B.reshape(B.shape[0], 1)
print(f"A:\n{A}\n")
print(f"B:\n{B}\n")
print(f"A + B:\n{A + B}\n")

A:
[[7]
 [0]
 [7]
 [8]]

B:
[[1.]
 [1.]
 [1.]
 [1.]]

A + B:
[[8.]
 [1.]
 [8.]
 [9.]]



- Summary:
    - Here is a quick summary of the information about NumPy.
    - {{local:python_numpy_broadcasting.png}}