# MATH WITH NUMPY

In [2]:
import numpy as np

In [3]:
np.random.seed(0)
A = np.random.randint(0, 10, [2, 3])
A

array([[5, 0, 3],
       [3, 7, 9]])

## N Dimentional Array Methods

- Unsurprisingly, the sum method will give us the sum of the whole array, the rows, the columns, etc.

In [4]:
A.sum()

27

- Passing a value to the axis parameter indicates the axis we want to add. This gives us a new list of the values added by those axis.

In [5]:
A.sum(axis=0)

array([ 8,  7, 12])

In [6]:
A.sum(axis=1)

array([ 8, 19])

- Can do a "cumulative sum" with .cumsum which will add the first value, then the second, then the third.. etc.

In [7]:
A.cumsum()

array([ 5,  5,  8, 11, 18, 27])

- Product: every element multiplied together.

In [8]:
A.prod()

0

- Can also do an "cumulative product" similar to cumulative sum.

In [9]:
A.cumprod()

array([5, 0, 0, 0, 0, 0])

- Find the minimum value in the table.
- Can also find the minimum in an specific axis.

In [10]:
A.min()

0

In [11]:
A.min(axis=0)

array([3, 0, 3])

- If we need to find the position in the array of the minimum value we have "argmin".
    - "argmax" exists as well.

In [12]:
A.argmin()

1

- Likewise, there are sort methods. 
    - Sort will sort the elements
    - Argsort will sort but return the index of the sort.
    - In other words, the first number returned will be the index of the smalles number, then the second number returned will be the index of the second smallest number, etc.

In [13]:
A.sort()
A

array([[0, 3, 5],
       [3, 7, 9]])

In [29]:
A.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2]])

## Methodes for ND Arrays

- Here we are returning the minimum arguments' index along the given axis.

In [15]:
A.argmin(axis=0)

array([0, 0, 0])

- To calculate the exponencial f(x) = e^x {{https://en.wikipedia.org/wiki/Exponential_function}}
    - Run the exp() method, but this method does not belong to A, it belongs to numpy, so the syntax is a little different.

In [31]:
np.exp(A)

array([[1.00000000e+00, 2.00855369e+01, 1.48413159e+02],
       [2.00855369e+01, 1.09663316e+03, 8.10308393e+03]])

- Similarly, you can take the log of an array with the same syntax.
- Note: If there is a 0 in your set, you'll get an error with log because that's imposible, but the rest of the array will still calculate.

In [32]:
np.log(A)

/tmp/ipykernel_43951/2475394391.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(A)


array([[      -inf, 1.09861229, 1.60943791],
       [1.09861229, 1.94591015, 2.19722458]])

- Similarly, you can do this for any other math functions as well.

In [33]:
np.sin(A)

array([[ 0.        ,  0.14112001, -0.95892427],
       [ 0.14112001,  0.6569866 ,  0.41211849]])

## Statistics

- Some functions we have for tables related to statistics inlude:
    - A.min(axis), A.argmin(axis)
    - A.max(axis), A.argmax(axis)
    - A.mean(axis)
    - A.var(axis)
    - A.stdaxis)

In [36]:
A

array([[0, 3, 5],
       [3, 7, 9]])

In [34]:
A.min()

0

In [37]:
A.argmax()      # This says, "Which index is the largest value?"

5

In [40]:
A.mean(axis=1)

array([2.66666667, 6.33333333])

In [41]:
A.var(axis=1)       # This is for the variance {{https://en.wikipedia.org/wiki/Variance}}

array([4.22222222, 6.22222222])

In [42]:
A.std()             # This finds the standard deviation of a set {{https://en.wikipedia.org/wiki/Standard_deviation}}

2.9297326385411577

- Of note is the function corrcoef - "Correlation Coeficient"
    - More can be found here: {{https://en.wikipedia.org/wiki/Pearson_correlation_coefficient}}
- This is useful for machine leanring because it helps us find the correlation between different rows and columns.

In [43]:
np.corrcoef(A)

array([[1.        , 0.99717646],
       [0.99717646, 1.        ]])

- What do we do with this?
- This method generates a new table of correlation coeficients that tell us the correlation between different lines.
- Note that there are 1 1's and the othe numbers are the same as well.
np.corrcoef(A) =    [[  ,   L1,   L2]
                     [L1,    1, L1L2]
                     [L2, L2L1,    1]]
    - Some resources to understand this:
        {{https://www.youtube.com/watch?v=ugd4k3dC_8Y}}
        {{https://youtu.be/RwFiNlL4Q8g?list=PLO_fdPEVlfKqMDNmCFzQISI2H_nJcEDJq&t=513}}
        
